/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package workingtime.views;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import workingtime.database.Conexion;
import workingtime.model.ResetFields;

/**
 *
 * @author Lidia Parral
 */
public class AddDocScreen extends javax.swing.JFrame {

    public ResetFields reset = new ResetFields();

    Conexion conn = new Conexion();
    Connection conect;

    DefaultTableModel modelo;

    PreparedStatement ps;
    Statement st;

    ResultSet rs;

    String sql;
    String name;
    String date;
    String typeDoc;
    String idEmp;
    String path;
    
    JFileChooser selected = new JFileChooser();
    byte[] img;
    
    FileInputStream input;
    FileOutputStream out;
    File file;
    
    
    /**
     * Creates new form AddDocumentoScreen
     */
    public AddDocScreen() {
        initComponents();      
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        txtPathDoc.setVisible(false);
        lblIdEmp.setVisible(false);
        lblDateUpdateDoc.setFont(new Font("Century Gothic",Font.BOLD,12));
        lblNamDoc.setFont(new Font("Century Gothic",Font.BOLD,12));
        lblDateUpdateDoc.setFont(new Font("Century Gothic",Font.BOLD,12));
        btnAddDoc.setFont(new Font("Century Gothic",Font.BOLD,12));
        btnSaveDoc.setFont(new Font("Century Gothic",Font.BOLD,12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTypeDoc = new javax.swing.JLabel();
        lblNamDoc = new javax.swing.JLabel();
        lblDateUpdateDoc = new javax.swing.JLabel();
        txtNomDoc = new javax.swing.JTextField();
        dtFechaSubDoc = new com.toedter.calendar.JDateChooser();
        cmbTypeDoc = new javax.swing.JComboBox<>();
        btnAddDoc = new javax.swing.JButton();
        btnSaveDoc = new javax.swing.JButton();
        lblIdEmp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPathDoc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(470, 334));

        jPanel1.setMaximumSize(new java.awt.Dimension(470, 447));
        jPanel1.setMinimumSize(new java.awt.Dimension(470, 447));
        jPanel1.setName(""); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(470, 289));
        jPanel3.setMinimumSize(new java.awt.Dimension(470, 289));

        lblTypeDoc.setText("Tipo de documento:");

        lblNamDoc.setText("Nombre del documento:");

        lblDateUpdateDoc.setText("Fecha de subida:");

        txtNomDoc.setEnabled(false);
        txtNomDoc.setFocusable(false);

        dtFechaSubDoc.setBackground(new java.awt.Color(255, 255, 255));
        dtFechaSubDoc.setMaxSelectableDate(new Date());

        cmbTypeDoc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbTypeDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "Excel", "Word" }));

        btnAddDoc.setBackground(new java.awt.Color(255, 126, 60));
        btnAddDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDoc.setText("AÑADIR");
        btnAddDoc.setToolTipText("Este botón permite añadir el documento");
        btnAddDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });

        btnSaveDoc.setBackground(new java.awt.Color(38, 70, 166));
        btnSaveDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveDoc.setText("GUARDAR");
        btnSaveDoc.setToolTipText("Este botón permite guardar el documento.");
        btnSaveDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDocActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\parra\\Downloads\\bolsa-de-valores (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 449, Short.MAX_VALUE)
                .addComponent(lblIdEmp)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateUpdateDoc)
                            .addComponent(txtNomDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamDoc)
                            .addComponent(lblTypeDoc)
                            .addComponent(cmbTypeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFechaSubDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAddDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnSaveDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblIdEmp)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTypeDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTypeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblNamDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateUpdateDoc))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtFechaSubDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtPathDoc.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtPathDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtPathDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        btnAddDoc.setBackground(new Color(145, 150, 255));
        if(selected.showDialog(this, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            file = selected.getSelectedFile();
            if(file.canRead()){
                if(file.getName().endsWith(".pdf") || file.getName().endsWith(".doc") || file.getName().endsWith(".docx") 
                        || file.getName().endsWith(".xlsx") || file.getName().endsWith(".xls")){
                    try {
                        img = addFile(file);
                        txtPathDoc.setText(file.getAbsolutePath());
                        txtNomDoc.setText(file.getName());
                    } catch (IOException ex) {
                        Logger.getLogger(AddDocScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No puede abrir un archivo con esa extensión.\nSólo permite las siguientes extensiones:\n"
                        + ".pdf,.doc,.docx,.xls,.xlsx", "DOCUMENTOS", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        btnAddDoc.setBackground(new Color(255,126,60));
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void btnSaveDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDocActionPerformed
        btnSaveDoc.setBackground(new Color(252, 201, 131));
        if(selected.showDialog(this, "GUARDAR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            file = selected.getSelectedFile();
            if(!file.getName().endsWith(".pdf") && !file.getName().endsWith(".doc") && !file.getName().endsWith(".docx") 
                        && !file.getName().endsWith(".xlsx") && !file.getName().endsWith(".xls")){
                JOptionPane.showMessageDialog(null, "No puede guardar un archivo con esa extensión.\nSólo permite las siguientes extensiones:\n"
                        + ".pdf,.doc,.docx,.xls,.xlsx", "DOCUMENTOS", JOptionPane.ERROR_MESSAGE);
            } else {
                String respuesta = saveFile(file, img);
                saveDocument();
                if(respuesta != null){
                    JOptionPane.showMessageDialog(null, respuesta);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "DOCUMENTOS", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
         btnSaveDoc.setBackground(new Color(38,70,166));
    }//GEN-LAST:event_btnSaveDocActionPerformed

    public byte[] addFile(File archivo) throws IOException{
        byte[] contenido = new byte[1024*1000];
        try{
            input = new FileInputStream(archivo);
            input.read(contenido);
        } catch(FileNotFoundException e){
            
        }    
        return contenido;
    }
    
    
    public String saveFile(File archivo, byte[] contenido){
        String resp = null;       
        try{
            out = new FileOutputStream(archivo);
            out.write(contenido);
            resp = "Se ha guardado el archivo correctamente.";
        }catch(IOException e){
            
        } 
        return resp;   
    }
    
    
    public void saveDocument(){
        idEmp = lblIdEmp.getText();
        name = txtNomDoc.getText();
        path = txtPathDoc.getText();
        date = new SimpleDateFormat("dd-MM-yyyy").format(dtFechaSubDoc.getDate());

        try {
            typeDocuments();
            if (name.equals("") || date.equals("")) {
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos.", "Validación campos", JOptionPane.ERROR_MESSAGE);
            } else {
                sql = "INSERT INTO documentos_empleado(IdEmpleado,TipoDocumento,NombreDoc,RutaArchivo,FechaSubida) VALUES "
                        + "('" + idEmp + "','" + typeDoc + "','" + name + "','" + path + "'," 
                        + "STR_TO_DATE('" + date + "','%d-%m-%Y')" + ")";

                conect = conn.getConexion();
                st = conect.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Registro con éxito", "DOCUMENTOS", JOptionPane.INFORMATION_MESSAGE);               
            }
        } catch (HeadlessException | SQLException ex) {
            System.err.println("Error:" + ex);
        }
    }
    
     void typeDocuments() {
        switch (cmbTypeDoc.getSelectedIndex()) {
            case 0:
                typeDoc = "PDF";
                break;
            case 1:
                typeDoc = "WORD";
                break;
            case 2:
                typeDoc = "EXCEL";
                break;
            default:
                throw new AssertionError();
        }

    }
     

         
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/logotipo.png"));
        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddDocScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddDoc;
    public javax.swing.JButton btnSaveDoc;
    public javax.swing.JComboBox<String> cmbTypeDoc;
    public com.toedter.calendar.JDateChooser dtFechaSubDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDateUpdateDoc;
    public javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblNamDoc;
    private javax.swing.JLabel lblTypeDoc;
    public javax.swing.JTextField txtNomDoc;
    public javax.swing.JTextField txtPathDoc;
    // End of variables declaration//GEN-END:variables
}
