/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package workingtime.views.Time;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia Parral
 */
public class AbsencesLeavesScreen extends javax.swing.JFrame {

    public String typeAbs;
    public String dateFin;
    public String dateStart;
    
    int day;
    /**
     * Creates new form AbsencesLeavesScreen
     */
    public AbsencesLeavesScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jckbBajaEnfCom = new javax.swing.JCheckBox();
        jckbEmpProf = new javax.swing.JCheckBox();
        jckbAccidenteLab = new javax.swing.JCheckBox();
        jckbPat = new javax.swing.JCheckBox();
        jckbMat = new javax.swing.JCheckBox();
        dtDateStart = new com.toedter.calendar.JDateChooser();
        dtDateFin = new com.toedter.calendar.JDateChooser();
        btnSaveTipoAus = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jckbBajaEnfCom.setText("Baja por enfermedad común");
        jckbBajaEnfCom.setToolTipText("");

        jckbEmpProf.setText("Baja por enfermedad profesional");

        jckbAccidenteLab.setText("Baja por accidente laboral");

        jckbPat.setText("Baja por paternidad");
        jckbPat.setToolTipText("");

        jckbMat.setText("Baja por maternidad");

        dtDateStart.setMinSelectableDate(new Date());
        dtDateStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtDateStartPropertyChange(evt);
            }
        });

        dtDateFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dtDateFinPropertyChange(evt);
            }
        });

        btnSaveTipoAus.setBackground(new java.awt.Color(38, 70, 166));
        btnSaveTipoAus.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveTipoAus.setText("GUARDAR");
        btnSaveTipoAus.setToolTipText("Este botón permite guarda la ausencia.");
        btnSaveTipoAus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSaveTipoAus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTipoAusActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(204, 204, 204));
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("CANCELAR");
        btnReturn.setToolTipText("Este botón permite volver a la página anterior.");
        btnReturn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de Inicio:");

        jLabel2.setText("Fecha de Fin:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jckbBajaEnfCom)
                            .addComponent(jckbPat))
                        .addContainerGap(309, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jckbEmpProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(dtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jckbAccidenteLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(dtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jckbMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveTipoAus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jckbBajaEnfCom)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jckbEmpProf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jckbAccidenteLab)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(dtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jckbPat)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jckbMat)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveTipoAus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveTipoAusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTipoAusActionPerformed
        btnSaveTipoAus.setBackground(new Color(252, 201, 131));
        chooseTypeLeave();
        dateStart = new SimpleDateFormat("dd-MM-yyyy").format(dtDateStart.getDate());
        dateFin = new SimpleDateFormat("dd-MM-yyyy").format(dtDateFin.getDate());
        btnSaveTipoAus.setBackground(new Color(38, 70, 166));
        this.hide();
    }//GEN-LAST:event_btnSaveTipoAusActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void dtDateStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtDateStartPropertyChange
         if ("date".equals(evt.getPropertyName())) {
            Date nuevaFecha = (Date) evt.getNewValue();
            if (notWorkingDay(nuevaFecha)) {
                JOptionPane.showMessageDialog(null, "La fecha seleccionada no es válida.", "VALIDACIÓN DE CAMPOS", JOptionPane.ERROR_MESSAGE);
                dtDateStart.setDateFormatString("");
            }
        }
    }//GEN-LAST:event_dtDateStartPropertyChange

    private void dtDateFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dtDateFinPropertyChange
         if ("date".equals(evt.getPropertyName())) {
            Date nuevaFecha = (Date) evt.getNewValue();
            if (notWorkingDay(nuevaFecha)) {
                JOptionPane.showMessageDialog(null, "La fecha seleccionada no es válida.", "VALIDACIÓN DE CAMPOS", JOptionPane.ERROR_MESSAGE);
                dtDateFin.setDateFormatString("");
            }
        }
    }//GEN-LAST:event_dtDateFinPropertyChange

    private String chooseTypeLeave(){
        if(jckbBajaEnfCom.isSelected()){
            typeAbs = "BAJA ENFERMEDAD COMUN";
        } else if(jckbEmpProf.isSelected()){
            typeAbs = "BAJA ENFERMEDAD PROFESIONAL";           
        } else if(jckbAccidenteLab.isSelected()){
            typeAbs = "BAJA ACCIDENTE LABORAL";           
        }else if(jckbMat.isSelected()){
            typeAbs = "BAJA POR MATERNIDAD";           
        }else if(jckbPat.isSelected()){
            typeAbs = "BAJA POR PATERNIDAD";           
        }
        return typeAbs;
    }
    
    
     private boolean notWorkingDay(Date fecha) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(fecha);

        day = calendar.get(Calendar.DAY_OF_WEEK);

        // Verificar si es sábado o domingo
        return day == Calendar.SATURDAY || day == Calendar.SUNDAY;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsencesLeavesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsencesLeavesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsencesLeavesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsencesLeavesScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AbsencesLeavesScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSaveTipoAus;
    private com.toedter.calendar.JDateChooser dtDateFin;
    private com.toedter.calendar.JDateChooser dtDateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox jckbAccidenteLab;
    private javax.swing.JCheckBox jckbBajaEnfCom;
    private javax.swing.JCheckBox jckbEmpProf;
    private javax.swing.JCheckBox jckbMat;
    private javax.swing.JCheckBox jckbPat;
    // End of variables declaration//GEN-END:variables
}
